using SevenSpices.Core.Items;

namespace SevenSpices.Tests.Items;

public static class ItemInstanceTests
{
    public static void RunAll()
    {
        Test_Definition_IsStored();
        Test_InstanceId_IsStored();
        Test_AutoGeneratedInstanceId_IsNotEmpty();
        Test_MultipleInstances_SameDefinition_HaveDistinctInstanceIds();
        Test_ExplicitInstanceId_IsPreserved();
        Test_NullDefinition_Throws();

        Console.WriteLine("All ItemInstanceTests passed.");
    }

    static ItemDefinition MakeItem() =>
        new("item_001", "辣椒酱");

    static void Test_Definition_IsStored()
    {
        var def = MakeItem();
        var inst = new ItemInstance(def, "instance_abc");
        Assert(ReferenceEquals(inst.Definition, def), "Definition must be stored as the same object reference");
        Assert(inst.Definition.Id == "item_001", "Definition.Id must be accessible via instance");
    }

    static void Test_InstanceId_IsStored()
    {
        var inst = new ItemInstance(MakeItem(), "instance_abc");
        Assert(inst.InstanceId == "instance_abc", "InstanceId must be stored correctly");
    }

    static void Test_AutoGeneratedInstanceId_IsNotEmpty()
    {
        var inst = new ItemInstance(MakeItem());
        Assert(!string.IsNullOrWhiteSpace(inst.InstanceId), "Auto-generated InstanceId must not be empty");
    }

    static void Test_MultipleInstances_SameDefinition_HaveDistinctInstanceIds()
    {
        var def = MakeItem();
        var a = new ItemInstance(def);
        var b = new ItemInstance(def);
        var c = new ItemInstance(def);

        Assert(ReferenceEquals(a.Definition, b.Definition) && ReferenceEquals(b.Definition, c.Definition),
            "All instances must share the same Definition object");
        Assert(a.InstanceId != b.InstanceId, "Instance IDs must be unique (a vs b)");
        Assert(b.InstanceId != c.InstanceId, "Instance IDs must be unique (b vs c)");
        Assert(a.InstanceId != c.InstanceId, "Instance IDs must be unique (a vs c)");
    }

    static void Test_ExplicitInstanceId_IsPreserved()
    {
        var def = new ItemDefinition("item_002", "醋");
        var inst = new ItemInstance(def, "fixed_id_999");
        Assert(inst.InstanceId == "fixed_id_999", "Explicit InstanceId must be preserved");
        Assert(inst.Definition.Id == "item_002", "Definition must be accessible alongside explicit InstanceId");
    }

    static void Test_NullDefinition_Throws()
    {
        try
        {
            _ = new ItemInstance(null!);
            Assert(false, "Null Definition must throw ArgumentNullException");
        }
        catch (ArgumentNullException) { }
    }

    static void Assert(bool condition, string message)
    {
        if (!condition)
            throw new Exception($"[FAIL] {message}");
    }
}
