using SevenSpices.Core.Customers;

namespace SevenSpices.Tests.Customers;

public static class CustomerInstanceTests
{
    public static void RunAll()
    {
        Test_InstanceId_IsStored();
        Test_DefinitionId_IsStored();
        Test_AutoGeneratedInstanceId_IsNotEmpty();
        Test_MultipleInstances_SameDefinitionId_HaveDistinctInstanceIds();
        Test_ExplicitInstanceId_IsPreserved();
        Test_EmptyDefinitionId_Throws();

        Console.WriteLine("All CustomerInstanceTests passed.");
    }

    static void Test_InstanceId_IsStored()
    {
        var inst = new CustomerInstance("customer_rare_001", "instance_abc");
        Assert(inst.InstanceId == "instance_abc", "InstanceId must be stored correctly");
    }

    static void Test_DefinitionId_IsStored()
    {
        var inst = new CustomerInstance("customer_rare_001", "instance_abc");
        Assert(inst.DefinitionId == "customer_rare_001", "DefinitionId must be stored correctly");
    }

    static void Test_AutoGeneratedInstanceId_IsNotEmpty()
    {
        var inst = new CustomerInstance("customer_rare_001");
        Assert(!string.IsNullOrWhiteSpace(inst.InstanceId), "Auto-generated InstanceId must not be empty");
    }

    static void Test_MultipleInstances_SameDefinitionId_HaveDistinctInstanceIds()
    {
        var a = new CustomerInstance("customer_rare_001");
        var b = new CustomerInstance("customer_rare_001");
        var c = new CustomerInstance("customer_rare_001");

        Assert(a.DefinitionId == b.DefinitionId && b.DefinitionId == c.DefinitionId,
            "All instances must share the same DefinitionId");
        Assert(a.InstanceId != b.InstanceId, "Instance IDs must be unique (a vs b)");
        Assert(b.InstanceId != c.InstanceId, "Instance IDs must be unique (b vs c)");
        Assert(a.InstanceId != c.InstanceId, "Instance IDs must be unique (a vs c)");
    }

    static void Test_ExplicitInstanceId_IsPreserved()
    {
        var inst = new CustomerInstance("customer_normal_001", "fixed_id_999");
        Assert(inst.InstanceId == "fixed_id_999", "Explicit InstanceId must be preserved");
        Assert(inst.DefinitionId == "customer_normal_001", "DefinitionId must be preserved alongside explicit InstanceId");
    }

    static void Test_EmptyDefinitionId_Throws()
    {
        try
        {
            _ = new CustomerInstance("");
            Assert(false, "Empty DefinitionId must throw ArgumentException");
        }
        catch (ArgumentException) { }
    }

    static void Assert(bool condition, string message)
    {
        if (!condition)
            throw new Exception($"[FAIL] {message}");
    }
}
